### ISSUE TITLE
accuracy  problem

### ISSUE THREAD

**Issue by Mrzhangxiaohua** [wzell/cmd#8]
I am interested in your  work and i had run your code of cmd successfully but i still have two problems.
1. the total accuracy on office31, am->wc, wc ->am, etc are lower than your paper results.
    my: acc-tst=0.5597484278229048; acc-tst-dr=0.6503144648090099
    yours:acc-tst = .676 +-006 ;    acc-tst-dr= .770  +- 006
2. i use tensorflow==0.12.1 and other same as you, how can i put it on GPU
(i use keras function: from keras.utils.multi_gpu_utils import multi_gpu_model,  
with no err but run it  i got ModuleNotFoundError: No module named 'keras.utils.multi_gpu_utils')

**Comment by wzell** [comment]
Hallo Mrzhangxiaohua,

nice to see Your interest in our project!

You are using a different framework than we do. Please install the libraries as described in the requirements and requirements.txt.

Since the domain adaptation works (accuracy improvement of 10% is the same as in our experiments), I assume that the base model VGG16 is somehow different than in our implementations.

The right framework should change this problems. However, if you want to proceed with your framework I suggest to contact the respective pages.

I allow myself to close this issue, as it is clearly related to some untested differences in the software other than specified in the requirements.

**Comment by Mrzhangxiaohua** [comment]
thanks for your replying me! flower
I use the same framwork and code, but keras 1.1 require tf as base,so i use tensorflow==0.12.1
and the data and vgg16 weight from your readme link.
and wc->dslr, dslr->wc is right(same as your paper), others are lower, so i don't known where i did wrong

**Comment by wzell** [comment]
Our implementation is based on theano not tensorflow. Keras does NOT require tensorflow but it can also be based on Theano.

**Comment by Mrzhangxiaohua** [comment]
ok, i will have a try. Thank you very much

**Comment by wzell** [comment]
Maybe this helps you also: There is an extended version of our work available in https://github.com/wzell/mann

There is an illustrative example that shows how to update the code to newer versions of keras and tensorflow.

**Comment by Mrzhangxiaohua** [comment]
thank you very much
